services:
    app:
        build: .
        container_name: bluey
        restart: always
        volumes:
            - .:/var/www/html
  
    web:
        build:
            context: ./nginx-docker
            dockerfile: Dockerfile
        image: nginx:alpine
        container_name: bluey-web
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html

